souffle: souffle::NullableVector< T > Class Template Reference
souffle::NullableVector< T > Class Template Reference
Public Member Functions
const std::vector< T > & getVector () const
bool isValid () const
NullableVector ()=default
NullableVector (std::vector< T > vector)
Private Attributes
bool valid = false
std::vector< T > vector
Detailed Description
template<class T>
class souffle::NullableVector< T >
Definition at line 42 of file InlineRelationsTransformer.cpp.
Constructor & Destructor Documentation
NullableVector() [1/2]
template<class T> souffle::NullableVector< T >::NullableVector () default
NullableVector() [2/2]
template<class T> souffle::NullableVector< T >::NullableVector (std::vector< T > vector) inline
Definition at line 49 of file InlineRelationsTransformer.cpp.
 : vector(std::move(vector)), valid(true) {}
Member Function Documentation
getVector()
template<class T> const std::vector<T>& souffle::NullableVector< T >::getVector () const inline
Definition at line 55 of file InlineRelationsTransformer.cpp.
References souffle::getInlinedLiteral(), and souffle::NullableVector< T >::vector.
Referenced by souffle::formNegatedLiterals(), souffle::getInlinedArgument(), souffle::getInlinedAtom(), souffle::getInlinedClause(), souffle::getInlinedLiteral(), and souffle::inlineBodyLiterals().
{
         assert(valid && "Accessing invalid vector!");
         return vector;
     }
isValid()
template<class T> bool souffle::NullableVector< T >::isValid () const inline
Definition at line 51 of file InlineRelationsTransformer.cpp.
References souffle::NullableVector< T >::valid.
Referenced by souffle::formNegatedLiterals(), souffle::getInlinedArgument(), souffle::getInlinedAtom(), souffle::getInlinedClause(), souffle::getInlinedLiteral(), and souffle::inlineBodyLiterals().
{
         return valid;
     }
Field Documentation
valid
template<class T> bool souffle::NullableVector< T >::valid = false private
Definition at line 45 of file InlineRelationsTransformer.cpp.
Referenced by souffle::NullableVector< T >::isValid().
vector
template<class T> std::vector<T> souffle::NullableVector< T >::vector private
Definition at line 44 of file InlineRelationsTransformer.cpp.
Referenced by souffle::NullableVector< T >::getVector().
The documentation for this class was generated from the following file:
InlineRelationsTransformer.cpp